# Generated by Django 5.2.8 on 2025-11-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_cargo_created_by_servidor_celular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_ocorrencia', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('TIPO_ACIDENTE', 'Acidente típico'), ('TRAJETO', 'Acidente de trajeto'), ('DOENCA', 'Doença ocupacional')], max_length=20)),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave'), ('IMINENTE', 'Grave com risco iminente')], default='LEVE', max_length=20)),
                ('descricao', models.TextField()),
                ('houve_afastamento', models.BooleanField(default=False)),
                ('dias_afastamento', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('testemunhas', models.TextField(blank=True, help_text='Nomes das testemunhas, se houver.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acidentes', to='core.servidor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acidentes', to='core.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acidentes', to='core.unidade')),
            ],
            options={
                'verbose_name': 'Acidente',
                'verbose_name_plural': 'Acidentes',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='CAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NAO_ENVIADA', 'Não enviada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='NAO_ENVIADA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('acidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='acidentes.acidente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('responsavel_emissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAT',
                'verbose_name_plural': 'CATs',
            },
        ),
    ]
