# Generated by Django 5.2.8 on 2025-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='acidente',
            name='tipo',
            field=models.CharField(choices=[('TIPO_ACIDENTE', 'Acidente tipico'), ('TRAJETO', 'Acidente de trajeto'), ('DOENCA', 'Doenca ocupacional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('NAO_ENVIADA', 'Nao enviada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='NAO_ENVIADA', max_length=20),
        ),
    ]
