# Generated by Django 5.2.8 on 2025-11-26 14:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servidor',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servidor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servidor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='pis',
            field=models.CharField(blank=True, max_length=15, verbose_name='PIS/PASEP'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setor',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='bairro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{5}-?[0-9]{3}$', 'CEP no formato 99999-999')]),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='unidade',
            name='complemento',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='unidade',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unidade',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unidade',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{3}\\.?[0-9]{3}\\.?[0-9]{3}-?[0-9]{2}$', 'CPF no formato 999.999.999-99')]),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Opcional: associa o servidor a um usuário do sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
