# Generated by Django 5.2.8 on 2025-11-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_cargo_created_by_servidor_celular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ADMISSIONAL', 'Admissional'), ('PERIODICO', 'Periódico'), ('RETORNO', 'Retorno ao trabalho'), ('MUDANCA', 'Mudança de função'), ('DEMISSIONAL', 'Demissional')], max_length=20)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, help_text='Data limite para novo exame.', null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('VENCIDO', 'Vencido')], default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='core.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='core.unidade')),
            ],
            options={
                'verbose_name': 'Exame Ocupacional',
                'verbose_name_plural': 'Exames Ocupacionais',
                'ordering': ['-data_realizacao', 'servidor__nome'],
            },
        ),
    ]
