# Generated by Django 5.2.8 on 2025-11-27 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_cargo_created_by_servidor_celular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('ca', models.CharField(blank=True, max_length=20, verbose_name='CA')),
                ('validade_ca', models.DateField(blank=True, help_text='Data de validade do CA (se aplicavel)', null=True)),
                ('categoria', models.CharField(blank=True, help_text='Ex.: Protecao respiratoria, ocular, auditiva', max_length=80)),
                ('tamanho', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_entrega', models.DateField()),
                ('data_validade', models.DateField(blank=True, help_text='Validade do equipamento entregue', null=True)),
                ('status', models.CharField(choices=[('ENTREGUE', 'Entregue'), ('PENDENTE', 'Pendente'), ('DEVOLVIDO', 'Devolvido')], default='ENTREGUE', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_epi', to='core.servidor')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='epi.epi')),
            ],
            options={
                'verbose_name': 'Entrega de EPI',
                'verbose_name_plural': 'Entregas de EPI',
                'ordering': ['-data_entrega'],
            },
        ),
    ]
